/*
@authors: LIS
Couoh, Eliezer
Cruz, Hilda
Garcilazo, Rosaura
*/

package App;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author compax
 */
public class Estrenos extends javax.swing.JFrame {

    /**
     * Creates new form Estrenos
     */
    public Estrenos() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
        txtaIT.setEditable(false);
        txtaIT.setText(horarioIT());
        
        txtaCOCO.setEditable(false);
        txtaCOCO.setText(horarioCOCO());
        
        txtaSELE.setEditable(false);
        txtaSELE.setText(horarioSELE());                
        
    }
    
    
    private String horarioIT(){
        
        String it =  ("\t\t***** IT *****\n\n" +
                    "HORA: 16:20hrs\t3D\tSALA: CC3\n" +
                    "HORA: 16:20hrs\t4D\tSALA: CC4\n" +
                    "HORA: 20:00hrs\t3D\tSALA: CC3");
        
        return it;        
    }
    
    private String horarioCOCO(){
        String coco =  ("\t\t***** COCO *****\n\n" +
                    "HORA: 13:00hrs\t4D\tSALA: C4\n" +
                    "HORA: 15:00hrs\tTr\tSALA: C1\n" +
                    "HORA: 17:00hrs\t3D\tSALA: C3");
        
        return coco;    
    }
    
    private String horarioSELE(){
        
        String sele =  ("\t\t***** SELENA *****\n\n" +
                    "HORA: 13:00hrs\tTr\tSALA: H5\n" +
                    "HORA: 17:00hrs\tTr\tSALA: H5\n" +
                    "HORA: 20:00hrs\tTr\tSALA: H5");
        
        return sele;        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        MoviePanel = new javax.swing.JPanel();
        panelIT = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCOCO = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelSELE = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        scPanelIT = new javax.swing.JScrollPane();
        txtaIT = new javax.swing.JTextArea();
        scPanelCOCO = new javax.swing.JScrollPane();
        txtaCOCO = new javax.swing.JTextArea();
        scPanelSELE = new javax.swing.JScrollPane();
        txtaSELE = new javax.swing.JTextArea();
        lbTITLE = new javax.swing.JLabel();
        btnCLOSE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setUndecorated(true);

        MainPanel.setBackground(new java.awt.Color(204, 0, 51));
        MainPanel.setForeground(new java.awt.Color(0, 102, 102));

        MoviePanel.setBackground(new java.awt.Color(0, 0, 0));

        panelIT.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/41a6npsf3cL._SY300_.jpg"))); // NOI18N

        javax.swing.GroupLayout panelITLayout = new javax.swing.GroupLayout(panelIT);
        panelIT.setLayout(panelITLayout);
        panelITLayout.setHorizontalGroup(
            panelITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelITLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelITLayout.setVerticalGroup(
            panelITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelITLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        panelCOCO.setBackground(new java.awt.Color(51, 153, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/Coco.jpg"))); // NOI18N

        javax.swing.GroupLayout panelCOCOLayout = new javax.swing.GroupLayout(panelCOCO);
        panelCOCO.setLayout(panelCOCOLayout);
        panelCOCOLayout.setHorizontalGroup(
            panelCOCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCOCOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCOCOLayout.setVerticalGroup(
            panelCOCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCOCOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelSELE.setBackground(new java.awt.Color(51, 153, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/selena.jpg"))); // NOI18N

        javax.swing.GroupLayout panelSELELayout = new javax.swing.GroupLayout(panelSELE);
        panelSELE.setLayout(panelSELELayout);
        panelSELELayout.setHorizontalGroup(
            panelSELELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSELELayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        panelSELELayout.setVerticalGroup(
            panelSELELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSELELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtaIT.setColumns(20);
        txtaIT.setRows(5);
        scPanelIT.setViewportView(txtaIT);

        txtaCOCO.setColumns(20);
        txtaCOCO.setRows(5);
        scPanelCOCO.setViewportView(txtaCOCO);

        txtaSELE.setColumns(20);
        txtaSELE.setRows(5);
        scPanelSELE.setViewportView(txtaSELE);

        javax.swing.GroupLayout MoviePanelLayout = new javax.swing.GroupLayout(MoviePanel);
        MoviePanel.setLayout(MoviePanelLayout);
        MoviePanelLayout.setHorizontalGroup(
            MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoviePanelLayout.createSequentialGroup()
                .addGroup(MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MoviePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MoviePanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(scPanelIT, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MoviePanelLayout.createSequentialGroup()
                        .addComponent(panelCOCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MoviePanelLayout.createSequentialGroup()
                        .addComponent(scPanelCOCO, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSELE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MoviePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(scPanelSELE, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MoviePanelLayout.setVerticalGroup(
            MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MoviePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scPanelIT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scPanelSELE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelSELE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelIT, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(MoviePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelCOCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scPanelCOCO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        lbTITLE.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lbTITLE.setForeground(new java.awt.Color(255, 255, 255));
        lbTITLE.setText("CARTELERA");

        btnCLOSE.setBackground(new java.awt.Color(51, 153, 255));
        btnCLOSE.setForeground(new java.awt.Color(255, 255, 255));
        btnCLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/if_Close_1891023.png"))); // NOI18N
        btnCLOSE.setText("Cerrar");
        btnCLOSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCLOSEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MoviePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(lbTITLE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCLOSE)
                .addGap(329, 329, 329))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTITLE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MoviePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCLOSE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCLOSEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCLOSEMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_btnCLOSEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estrenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estrenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estrenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estrenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estrenos().setVisible(true);
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                
                getImage(ClassLoader.getSystemResource("Icono/Lee+co.png"));
                


        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MoviePanel;
    private javax.swing.JButton btnCLOSE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbTITLE;
    private javax.swing.JPanel panelCOCO;
    private javax.swing.JPanel panelIT;
    private javax.swing.JPanel panelSELE;
    private javax.swing.JScrollPane scPanelCOCO;
    private javax.swing.JScrollPane scPanelIT;
    private javax.swing.JScrollPane scPanelSELE;
    private javax.swing.JTextArea txtaCOCO;
    private javax.swing.JTextArea txtaIT;
    private javax.swing.JTextArea txtaSELE;
    // End of variables declaration//GEN-END:variables
}
