/*
@authors: LIS
Couoh, Eliezer
Cruz, Hilda
Garcilazo, Rosaura
*/

package App;

import Modulo.Cliente;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author compax
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        closePanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        IcCine = new javax.swing.JLabel();
        lbTITLE = new javax.swing.JLabel();
        RightMenuPanel = new javax.swing.JPanel();
        Ticket = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Cartelera = new javax.swing.JLabel();
        jBRegistro = new javax.swing.JButton();
        jBcomprar = new javax.swing.JButton();
        jBCartelera = new javax.swing.JButton();
        lbMenuTITLE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        MainPanel.setBackground(new java.awt.Color(182, 29, 69));

        leftPanel.setBackground(new java.awt.Color(0, 0, 0));

        closePanel.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/if_Close_1891023.png"))); // NOI18N
        jButton1.setText("cerrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout closePanelLayout = new javax.swing.GroupLayout(closePanel);
        closePanel.setLayout(closePanelLayout);
        closePanelLayout.setHorizontalGroup(
            closePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, closePanelLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(91, 91, 91))
        );
        closePanelLayout.setVerticalGroup(
            closePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        IcCine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/bloggif_5a1b4374bf182.png"))); // NOI18N

        lbTITLE.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        lbTITLE.setForeground(new java.awt.Color(255, 255, 255));
        lbTITLE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTITLE.setText("CINE FMAT");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(IcCine))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(closePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(IcCine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTITLE)
                .addGap(18, 18, 18)
                .addComponent(closePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        RightMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        RightMenuPanel.setForeground(new java.awt.Color(255, 255, 255));

        Ticket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/if_Achievement_award_prize_winner_shield_star_1886037 (1).png"))); // NOI18N

        Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/if_user-group_285648(1).png"))); // NOI18N

        Cartelera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/if_85Account_albums_screens_tabs_1886145 (1).png"))); // NOI18N

        jBRegistro.setBackground(new java.awt.Color(51, 153, 255));
        jBRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jBRegistro.setText("Agregar Usuario");
        jBRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBRegistroMouseClicked(evt);
            }
        });

        jBcomprar.setBackground(new java.awt.Color(51, 153, 255));
        jBcomprar.setForeground(new java.awt.Color(255, 255, 255));
        jBcomprar.setText("Comprar");
        jBcomprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBcomprarMouseClicked(evt);
            }
        });

        jBCartelera.setBackground(new java.awt.Color(51, 153, 255));
        jBCartelera.setForeground(new java.awt.Color(255, 255, 255));
        jBCartelera.setText("Cartelera");
        jBCartelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCarteleraMouseClicked(evt);
            }
        });

        lbMenuTITLE.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lbMenuTITLE.setForeground(new java.awt.Color(182, 29, 69));
        lbMenuTITLE.setText("MENÚ");

        javax.swing.GroupLayout RightMenuPanelLayout = new javax.swing.GroupLayout(RightMenuPanel);
        RightMenuPanel.setLayout(RightMenuPanelLayout);
        RightMenuPanelLayout.setHorizontalGroup(
            RightMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightMenuPanelLayout.createSequentialGroup()
                .addGroup(RightMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightMenuPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(RightMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(RightMenuPanelLayout.createSequentialGroup()
                                .addComponent(Cartelera)
                                .addGap(18, 18, 18)
                                .addComponent(jBCartelera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(RightMenuPanelLayout.createSequentialGroup()
                                .addComponent(Usuario)
                                .addGap(18, 18, 18)
                                .addComponent(jBRegistro))
                            .addGroup(RightMenuPanelLayout.createSequentialGroup()
                                .addComponent(Ticket)
                                .addGap(18, 18, 18)
                                .addComponent(jBcomprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(RightMenuPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lbMenuTITLE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        RightMenuPanelLayout.setVerticalGroup(
            RightMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightMenuPanelLayout.createSequentialGroup()
                .addGroup(RightMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(RightMenuPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Ticket))
                    .addGroup(RightMenuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbMenuTITLE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBcomprar)
                        .addGap(10, 10, 10)))
                .addGroup(RightMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightMenuPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Usuario))
                    .addGroup(RightMenuPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jBRegistro)))
                .addGroup(RightMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightMenuPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Cartelera))
                    .addGroup(RightMenuPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jBCartelera)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RightMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RightMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRegistroMouseClicked
       /* ArrayList<Cliente> clien = new ArrayList();
        try{
            FileOutputStream fs = new FileOutputStream("clientes.txt");
            ObjectOutputStream ob = new ObjectOutputStream(fs);
            ob.writeObject(clien);
            ob.close();
        }
        catch(FileNotFoundException e1){
            JOptionPane.showMessageDialog(null, e1.getMessage());
        }
        catch(IOException e2){
            JOptionPane.showMessageDialog(null, e2.getMessage());
        }*/
        new Registro_Cliente().setVisible(true);
    }//GEN-LAST:event_jBRegistroMouseClicked

    private void jBcomprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBcomprarMouseClicked
        new FUNCION().setVisible(true);
        this.dispose();
         
    }//GEN-LAST:event_jBcomprarMouseClicked

    private void jBCarteleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCarteleraMouseClicked
        // TODO add your handling code here:
        new Estrenos().setVisible(true);
    }//GEN-LAST:event_jBCarteleraMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                
                getImage(ClassLoader.getSystemResource("Icono/Lee+co.png"));
                


        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cartelera;
    private javax.swing.JLabel IcCine;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel RightMenuPanel;
    private javax.swing.JLabel Ticket;
    private javax.swing.JLabel Usuario;
    private javax.swing.JPanel closePanel;
    private javax.swing.JButton jBCartelera;
    private javax.swing.JButton jBRegistro;
    private javax.swing.JButton jBcomprar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbMenuTITLE;
    private javax.swing.JLabel lbTITLE;
    private javax.swing.JPanel leftPanel;
    // End of variables declaration//GEN-END:variables
}
