/*
@authors: LIS
Couoh, Eliezer
Cruz, Hilda
Garcilazo, Rosaura
 */

package Modulo;

public interface calcularPrecio {
    public void calcularPrecio();
    /*
    MÉTODO DE INTERFAZ PARA CALCULAR EL PRECIO DEL BOLETO DEPENDIENDO SI CUENTA CON CUENTA CLIENTE ESPECIAL O NO
    SI SE POSEE UNA CUENTA ESPECIAL AL PRECIO TOTAL SE LE APLICARÁ UN DESCUENTO DEL 30% AL TOTAL
    DE LO CONTRARIO SIMPLEMENTE SE CALCULA EL PRECIO TOTAL DEPENDIENDO DEL TIPO DE FUNCIÓN:
        LA SALA TRADICIONAL TIENE UN COSTO DE 65$ POR PERSONA
        SALA 3D ES SALA TRADICIONAL MAS UN 20% EXTRA c/boleto
        SALA 4D ES SALA TRADICIONAL MAS UN 35% EXTRA c/boleto
    */
}
